version: "3"
services:

  zookeeper1:
    image: wurstmeister/zookeeper:3.4.6
    hostname: zookeeper1
    container_name: zookeeper1
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_SERVERS: zookeeper1:2888:3888

  kafka1:
    image: wurstmeister/kafka:2.11-1.1.0
    hostname: kafka1
    container_name: kafka1
    ports:
      - "9092:9092"
      - "9999:9999"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka1
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper1:2181"
      KAFKA_CREATE_TOPICS: sales-topic:1:1
    depends_on:
      - zookeeper1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  database:
    image: postgres:10.4-alpine
    container_name: database
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 8000:5432
    volumes:
      - ./services/database/schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - ./services/database/seed.sql:/docker-entrypoint-initdb.d/2-seed.sql
  
  producer:
    build: ./services/producer
    container_name: producer
    command: sh -c "dockerize -wait tcp://zookeeper1:2181 -wait tcp://kafka1:9092 -wait tcp://database:5432 npm start"
    depends_on:
      - zookeeper1
      - kafka1
      - database
    environment:
      PGHOST: database
      PGPORT: 5432
      PGUSER: ${POSTGRES_USER}
      PGDATABASE: ${POSTGRES_USER}
      PGPASSWORD: ${POSTGRES_PASSWORD}
      PRODUCER_PORT: ${PRODUCER_PORT}
      KAFKA_ZOOKEEPER_CONNECT: zookeeper1:2181
    ports:
      - ${PRODUCER_PORT}:${PRODUCER_PORT}

  consumer:
    build: ./services/consumer
    container_name: consumer
    command: sh -c "dockerize -wait tcp://zookeeper1:2181 -wait tcp://kafka1:9092 -wait tcp://database:5432 npm start"
    depends_on:
      - zookeeper1
      - kafka1
      - database
    environment:
      PGHOST: database
      PGPORT: 5432
      PGUSER: ${POSTGRES_USER}
      PGDATABASE: ${POSTGRES_USER}
      PGPASSWORD: ${POSTGRES_PASSWORD}
      KAFKA_ZOOKEEPER_CONNECT: zookeeper1:2181
